export enum Permissions {
  ROLE_PERMISSION_CREATE = 'role_permission:create',
  ROLE_PERMISSION_READ = 'role_permission:read',
  ROLE_PERMISSION_UPDATE = 'role_permission:update',
  ROLE_PERMISSION_DELETE = 'role_permission:delete',
  ROLE_PERMISSION_LIST = 'role_permission:list',
  ROLE_PERMISSION_MANAGE = 'role_permission:manage',
  ROLE_PERMISSION_ALL = 'role_permission:*',

  DEPARTMENTS_CREATE = 'departments:create',
  DEPARTMENTS_READ = 'departments:read',
  DEPARTMENTS_UPDATE = 'departments:update',
  DEPARTMENTS_DELETE = 'departments:delete',
  DEPARTMENTS_LIST = 'departments:list',
  DEPARTMENTS_MANAGE = 'departments:manage',
  DEPARTMENTS_ALL = 'departments:*',

  LOCATIONS_CREATE = 'locations:create',
  LOCATIONS_READ = 'locations:read',
  LOCATIONS_UPDATE = 'locations:update',
  LOCATIONS_DELETE = 'locations:delete',
  LOCATIONS_LIST = 'locations:list',
  LOCATIONS_MANAGE = 'locations:manage',
  LOCATIONS_ALL = 'locations:*',

  DEPARTMENT_LEAVE_APPROVERS_CREATE = 'department_leave_approvers:create',
  DEPARTMENT_LEAVE_APPROVERS_READ = 'department_leave_approvers:read',
  DEPARTMENT_LEAVE_APPROVERS_UPDATE = 'department_leave_approvers:update',
  DEPARTMENT_LEAVE_APPROVERS_DELETE = 'department_leave_approvers:delete',
  DEPARTMENT_LEAVE_APPROVERS_LIST = 'department_leave_approvers:list',
  DEPARTMENT_LEAVE_APPROVERS_MANAGE = 'department_leave_approvers:manage',
  DEPARTMENT_LEAVE_APPROVERS_ALL = 'department_leave_approvers:*',

  PENDING_USERS_CREATE = 'pending_users:create',
  PENDING_USERS_READ = 'pending_users:read',
  PENDING_USERS_UPDATE = 'pending_users:update',
  PENDING_USERS_DELETE = 'pending_users:delete',
  PENDING_USERS_LIST = 'pending_users:list',
  PENDING_USERS_MANAGE = 'pending_users:manage',
  PENDING_USERS_ALL = 'pending_users:*',


  LEAVES_CREATE = 'leaves:create',
  LEAVES_READ = 'leaves:read',
  LEAVES_UPDATE = 'leaves:update',
  LEAVES_DELETE = 'leaves:delete',
  LEAVES_LIST = 'leaves:list',
  LEAVES_MANAGE = 'leaves:manage',
  LEAVES_ALL = 'leaves:*',

  LEAVE_TYPE_LOCATIONS_CREATE = 'leave_type_locations:create',
  LEAVE_TYPE_LOCATIONS_READ = 'leave_type_locations:read',
  LEAVE_TYPE_LOCATIONS_UPDATE = 'leave_type_locations:update',
  LEAVE_TYPE_LOCATIONS_DELETE = 'leave_type_locations:delete',
  LEAVE_TYPE_LOCATIONS_LIST = 'leave_type_locations:list',
  LEAVE_TYPE_LOCATIONS_MANAGE = 'leave_type_locations:manage',
  LEAVE_TYPE_LOCATIONS_ALL = 'leave_type_locations:*',

  LEAVE_TYPE_DEPARTMENTS_CREATE = 'leave_type_departments:create',
  LEAVE_TYPE_DEPARTMENTS_READ = 'leave_type_departments:read',
  LEAVE_TYPE_DEPARTMENTS_UPDATE = 'leave_type_departments:update',
  LEAVE_TYPE_DEPARTMENTS_DELETE = 'leave_type_departments:delete',
  LEAVE_TYPE_DEPARTMENTS_LIST = 'leave_type_departments:list',
  LEAVE_TYPE_DEPARTMENTS_MANAGE = 'leave_type_departments:manage',
  LEAVE_TYPE_DEPARTMENTS_ALL = 'leave_type_departments:*',

  LEAVE_TYPE_SPECIAL_EMPLOYEES_CREATE = 'leave_type_special_employees:create',
  LEAVE_TYPE_SPECIAL_EMPLOYEES_READ = 'leave_type_special_employees:read',
  LEAVE_TYPE_SPECIAL_EMPLOYEES_UPDATE = 'leave_type_special_employees:update',
  LEAVE_TYPE_SPECIAL_EMPLOYEES_DELETE = 'leave_type_special_employees:delete',
  LEAVE_TYPE_SPECIAL_EMPLOYEES_LIST = 'leave_type_special_employees:list',
  LEAVE_TYPE_SPECIAL_EMPLOYEES_MANAGE = 'leave_type_special_employees:manage',
  LEAVE_TYPE_SPECIAL_EMPLOYEES_ALL = 'leave_type_special_employees:*',

  LEAVE_TYPES_CREATE = 'leave_types:create',
  LEAVE_TYPES_READ = 'leave_types:read',
  LEAVE_TYPES_UPDATE = 'leave_types:update',
  LEAVE_TYPES_DELETE = 'leave_types:delete',
  LEAVE_TYPES_LIST = 'leave_types:list',
  LEAVE_TYPES_MANAGE = 'leave_types:manage',
  LEAVE_TYPES_ALL = 'leave_types:*',

  ROLES_CREATE = 'roles:create',
  ROLES_READ = 'roles:read',
  ROLES_UPDATE = 'roles:update',
  ROLES_DELETE = 'roles:delete',
  ROLES_LIST = 'roles:list',
  ROLES_MANAGE = 'roles:manage',
  ROLES_ALL = 'roles:*',

  USER_EDUCATION_CREATE = 'user_education:create',
  USER_EDUCATION_READ = 'user_education:read',
  USER_EDUCATION_UPDATE = 'user_education:update',
  USER_EDUCATION_DELETE = 'user_education:delete',
  USER_EDUCATION_LIST = 'user_education:list',
  USER_EDUCATION_MANAGE = 'user_education:manage',
  USER_EDUCATION_ALL = 'user_education:*',

  EMERGENCY_CONTACTS_CREATE = 'emergency_contacts:create',
  EMERGENCY_CONTACTS_READ = 'emergency_contacts:read',
  EMERGENCY_CONTACTS_UPDATE = 'emergency_contacts:update',
  EMERGENCY_CONTACTS_DELETE = 'emergency_contacts:delete',
  EMERGENCY_CONTACTS_LIST = 'emergency_contacts:list',
  EMERGENCY_CONTACTS_MANAGE = 'emergency_contacts:manage',
  EMERGENCY_CONTACTS_ALL = 'emergency_contacts:*',

  USER_VISA_CREATE = 'user_visa:create',
  USER_VISA_READ = 'user_visa:read',
  USER_VISA_UPDATE = 'user_visa:update',
  USER_VISA_DELETE = 'user_visa:delete',
  USER_VISA_LIST = 'user_visa:list',
  USER_VISA_MANAGE = 'user_visa:manage',
  USER_VISA_ALL = 'user_visa:*',

  USER_EXTRA_INFORMATION_CREATE = 'user_extra_information:create',
  USER_EXTRA_INFORMATION_READ = 'user_extra_information:read',
  USER_EXTRA_INFORMATION_UPDATE = 'user_extra_information:update',
  USER_EXTRA_INFORMATION_DELETE = 'user_extra_information:delete',
  USER_EXTRA_INFORMATION_LIST = 'user_extra_information:list',
  USER_EXTRA_INFORMATION_MANAGE = 'user_extra_information:manage',
  USER_EXTRA_INFORMATION_ALL = 'user_extra_information:*',

  USER_SOCIAL_LINKS_CREATE = 'user_social_links:create',
  USER_SOCIAL_LINKS_READ = 'user_social_links:read',
  USER_SOCIAL_LINKS_UPDATE = 'user_social_links:update',
  USER_SOCIAL_LINKS_DELETE = 'user_social_links:delete',
  USER_SOCIAL_LINKS_LIST = 'user_social_links:list',
  USER_SOCIAL_LINKS_MANAGE = 'user_social_links:manage',
  USER_SOCIAL_LINKS_ALL = 'user_social_links:*',

  SOCIAL_LINK_TYPES_CREATE = 'social_link_types:create',
  SOCIAL_LINK_TYPES_READ = 'social_link_types:read',
  SOCIAL_LINK_TYPES_UPDATE = 'social_link_types:update',
  SOCIAL_LINK_TYPES_DELETE = 'social_link_types:delete',
  SOCIAL_LINK_TYPES_LIST = 'social_link_types:list',
  SOCIAL_LINK_TYPES_MANAGE = 'social_link_types:manage',
  SOCIAL_LINK_TYPES_ALL = 'social_link_types:*',

  USERS_CREATE = 'users:create',
  USERS_READ = 'users:read',
  USERS_UPDATE = 'users:update',
  USERS_DELETE = 'users:delete',
  USERS_LIST = 'users:list',
  USERS_MANAGE = 'users:manage',
  USERS_ALL = 'users:*'
 


}
